services:
  pathfinding:
    image: pathfinding:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
